apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-wtqzxn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-wtqzxn
    app.kubernetes.io/part-of: jvm-build-suite-application-noir
  name: jvm-build-suite-component-wtqzxn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-wtqzxn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-wtqzxn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-kiih-tenant/jvm-build-suite-application-noir/jvm-build-suite-component-wtqzxn@sha256:37fe4d488702fddc7a4cd3c76ab47934205f95042279c50a68625cb716e2c5b2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
